@local = http://localhost:3003

//Users//

//Get all users:
GET {{local}}/users/allUsers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzU2MzczOThjNjc4NzYxMGYwNDY1ZmMiLCJlbWFpbCI6InNlbGxidXk0NDJAZ21haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTY2ODA3MTYxNH0.57YpfZY-cTvAfiNJRDsN7G_LDkkkFl5yKKh17ZWlBZc


###Add new user:
POST  {{local}}/users/signup
Content-Type: application/json

{
    "name": "Mike",
    "city": "NewYork", 
    "email": "Mike@gmail.com",
    "password": "Mike770@",
    "phone": "0587611770",
    "favoriteCards": [] 
    }


### Login user:
POST  {{local}}/users/login
Content-Type: application/json

{
    "email": "Mike@gmail.com",
    "password": "Mike770@"
}


### Get user by token:
GET {{local}}/users/me
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU


### Update user by email:
PATCH {{local}}/users/update
user-email: Mike@gmail.com
Content-Type: application/json

{
    "phone": "0534416754"
}


### Delete user by id:
DELETE  {{local}}/users/deleteUser
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzU2MzczOThjNjc4NzYxMGYwNDY1ZmMiLCJlbWFpbCI6InNlbGxidXk0NDJAZ21haWwuY29tIiwiYWRtaW4iOnRydWUsImlhdCI6MTY2ODA3MTYxNH0.57YpfZY-cTvAfiNJRDsN7G_LDkkkFl5yKKh17ZWlBZc
user-id: 632ac688a05fb0e860110dbf


### Forgot pwd:
POST {{local}}/users/forgotPassword
Content-Type: application/json

{
    "email": "hodaya1abu@gmail.com"
}


###Add new user message:
POST {{local}}/msgs/newMsg
Content-Type: application/json

{
    "name": "Hodaya",
    "email": "hodaya@gmail.com",
    "msg": "your service is very good"
}



///////////////Cards///////////////

### Get all cards:
GET {{local}}/cards/allCards


### Get all cards by type
GET {{local}}/cards/Other


### Add new card:
POST {{local}}/cards
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU
Content-Type: application/json

{
    "image": "https://img.yad2.co.il/Pic/202211/09/3_0/o/y2_1_02659_20221109162454.jpeg?l=5&c=1&w=1024&h=768",
    "description": "Ninja grill pot new in packaging has not been used at all", 
    "price": "300",
    "productType": "Electronics"
}


### Find card by id:
Get {{local}}/cards/myCard
id-card: 636a106e745dd0eea4ffe472


### Update card by id:
PATCH  {{local}}/cards/myCard
id-card: 636a1743745dd0eea4ffe4b9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU
Content-Type: application/json

{
    "price":"590"
}


### Dalate card by id:
DELETE  {{local}}/cards/myCard
id-card: 636a1743745dd0eea4ffe4b9
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU


### Get all user cards
GET {{local}}/cards/myAllCards
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU


### Get all user favorite cards:
GET {{local}}/cards/favoriteCards
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU


### Add new favorite card:
PATCH {{local}}/cards/addFavorite
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU
Content-Type: application/json

{
    "cardId": "636a106e745dd0eea4ffe472"
}


### Remove favorite card:
PATCH {{local}}/cards/removeFavorite
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzVhM2QyMTE4Y2Q1MDhiZWY3YjNkNDciLCJlbWFpbCI6Ik1pa2VAZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE2NjgwNzE2NjR9.mgvsBunfI3BXE1YBEBwCr_TwtuaxUZW4Xbvz4qe6pmU
Content-Type: application/json

{
    "cardId": "636a106e745dd0eea4ffe472"
}
