@local = http://localhost:3003

//Users//

//Get all users:
GET {{local}}/users/allUsers
admin-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmVhNTk3MDk2ZTkzNTA4Mjg0NGYzOGIiLCJlbWFpbCI6ImlzLnRlaGlsYUBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYwNzY1MzA1fQ.YqHbbSisnltxr5y8Xcz64RuOafwJ2NPtemUg0NxjF_8

###Add new user:
POST  {{local}}/users/signup
Content-Type: application/json

{
    "name": "Tal",
    "city": "Tel-Aviv", 
    "email": "tal@gmail.com",
    "password": "Tall770@",
    "phone": "0587611770",
    "favoriteCards": ["6314693a7c62e0ae1f664fed", "6314693a7c62e0ae1f664fed"]
}


### Login user:
POST  {{local}}/users/login
Content-Type: application/json

{
    "email": "tal@gmail.com",
    "password": "Tall770@"
}


### Get user by token:
GET {{local}}/users/me
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzFkZmE4MjNkZDVmZTgxZTcwNmU1ODIiLCJlbWFpbCI6ImhvZGF5YUBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYyOTcyNjI4fQ.yf0-P-xUo-M7chpR2KWJkal3HCbuqdXQ_atw3rc2eYI

### Update user by email:
PATCH {{local}}/users/update
user-email: hodaya@gmail.com
Content-Type: application/json

{
    "city": "Tel Aviv"
}


### Delete user by id:
DELETE  {{local}}/users/deleteUser
admin-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE0NTUyOTM4MDVjZDMzNjRiN2E4MTYiLCJlbWFpbCI6ImhvZGF5YUBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYyMjc2OTA5fQ.wJkvQJXTHbdmjfgbbBY05K54BDNWrVbHle6J0fDWzYM
user-id: 631454cc3805cd3364b7a80d


### Get all the favorite card of user:
GET {{local}}/users/favoriteCards
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzJhYzgzYjQ4ZDMxOTNlYmZhZTExZGIiLCJlbWFpbCI6InRhbEBnbWFpbC5jb20iLCJhZG1pbiI6ZmFsc2UsImlhdCI6MTY2Mzc0ODE3NX0._eVXJhOAZ1kQLhuaWiWP69QI7UlRhlMNomgxCETndFI





### Forgot pwd:
PATCH {{{local}}}/users/forgotPassword
Content-Type: application/json

{
    "email": "hodaya1abu@gmail.com"
}


////// Messages from users ////////

###Get all users messages:
GET {{local}}/msgs/allUsersMsg
admin-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmVhNTk3MDk2ZTkzNTA4Mjg0NGYzOGIiLCJlbWFpbCI6ImlzLnRlaGlsYUBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYwNzY1MzA1fQ.YqHbbSisnltxr5y8Xcz64RuOafwJ2NPtemUg0NxjF_8


###Add new user message:
POST {{local}}/msgs/newMsg
Content-Type: application/json

{
    "name": "Hodaya",
    "email": "hodaya@gmail.com",
    "msg": "your service is very good"
}


//Cards//

### Get all cards:
GET {{local}}/cards/allCards


### Add new card:
POST {{local}}/cards
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzFkZmE4MjNkZDVmZTgxZTcwNmU1ODIiLCJlbWFpbCI6ImhvZGF5YUBnbWFpbC5jb20iLCJhZG1pbiI6dHJ1ZSwiaWF0IjoxNjYyOTcyNjI4fQ.yf0-P-xUo-M7chpR2KWJkal3HCbuqdXQ_atw3rc2eYI
Content-Type: application/json

{
    "image": "https://img.yad2.co.il/Pic/202208/29/3_2/o/y2_1_04819_20220829151457.jpeg?l=5&c=1&w=1024&h=768",
    "description": "very good", 
    "price": "600",
    "productType": "Watches"
}


### Find card by id:
Get {{local}}/cards/myCard
id-card: 630b335ba895014c972e4e5d


### Update card by id:
PATCH  {{local}}/cards/myCard
id-card: 6314693a7c62e0ae1f664fed
user-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmJkNWMxYzdiYjYyODYxNjhhZmIzYzciLCJlbWFpbCI6InRhbEBnbWFpbC5jb20iLCJpYXQiOjE2NTY1NzkxMDJ9.HLkM4NL6HgUVhvIK6ivK1LJHlGHASeDoe4BI8FCvYrI
Content-Type: application/json

{
   "image": "https://img.yad2.co.il/Pic/202202/07/3_0/o/y2_1_07458_20220207045916.jpeg?l=5&c=1&w=1024&h=768",
    "price":"890"
}


### Dalate card by id:
DELETE  {{local}}/cards/myCard
id-card: 63146beb7c62e0ae1f665012
user-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmVhNTgyYWE4MTc0YmYzZDhlZDE3YmYiLCJlbWFpbCI6ImhvZGF5YTFhYnVAZ21haWwuY29tIiwiaWF0IjoxNjU5NTI1NTM2fQ.BBLQbfY4ekwXyvpaPqPd5S9SfcNqSTfTs7_BgjFZ6_c


### Get all user cards
GET {{local}}/cards/myAllCards
user-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmVhNTgyYWE4MTc0YmYzZDhlZDE3YmYiLCJlbWFpbCI6ImhvZGF5YTFhYnVAZ21haWwuY29tIiwiaWF0IjoxNjU5NTI1NTM2fQ.BBLQbfY4ekwXyvpaPqPd5S9SfcNqSTfTs7_BgjFZ6_c

### Get all cards by type
GET {{local}}/cards/Sport